### PR TITLE
fix: always use function's namespace when invoking remote

### LINKED ISSUE #1167: Invoke command does not respect namespace in func.yaml
When running `func invoke`, if the function has been deployed to a non-default namespace, and that namespace exists in func.yaml, the command fails to use the configured namespace, requiring users to add the `--namespace` flag to `func invoke`.

```
❯ grep namespace func.yaml
namespace: func

❯ func invoke
Error: services.serving.knative.dev "viewer" not found

❯ func invoke --namespace func
Received response
{}%
```
/kind bug
/kind good-first-issue

### PR DESCRIPTION
**Pull request by lkingland**
- :bug: `invoke` should always use the function's current namespace
- :broom: remove unnecessary client instance from config constructor and prompt method signature
- :gift: adds a general invoke command test

/kind bug
Fixes #1167

### CODE REVIEW

**Review by lance — COMMENTED** [review]
Looks good! Would you mind adding a test? It seems `invoke.go` is our least covered files https://app.codecov.io/gh/knative-sandbox/kn-plugin-func.

**Comment by lkingland** [comment]
No problemmo

**Comment by matejvasek** [comment]
@lkingland 
>should always use the function's current namespace

Does this mean current `k8s` context, or the ns in `func.yaml`?

File: cmd/invoke.go [hunk 1]
```diff
@@ -135,8 +135,17 @@ func runInvoke(cmd *cobra.Command, args []string, newClient ClientFactory) (err
...
+	f, err := fn.NewFunction(cfg.Path)
+	if err != nil {
+		return
+	}
+	if !f.Initialized() {
+		return fmt.Errorf("'%v' does not contain an initialized function", cfg.Path)
+	}
+
 	// Client instance from env vars, flags, args and user prompts (if --confirm)
-	client, done := newClient(ClientConfig{Namespace: cfg.Namespace, Verbose: cfg.Verbose, InsecureSkipVerify: cfg.Insecure})
```
Comment (matejvasek) [inline cmd/invoke.go:139]: Shouldn't it be: `Namespace: f.Namespace` instead of deletion?

But it really depends on what is answer to https://github.com/knative-sandbox/kn-plugin-func/pull/1258#issuecomment-1255212969

Comment (matejvasek) [reply cmd/invoke.go:139]: is so then also test should be updated:
 ```diff
 diff --git a/cmd/invoke_test.go b/cmd/invoke_test.go
index e06d4292..bf20a3a0 100644
--- a/cmd/invoke_test.go
+++ b/cmd/invoke_test.go
@@ -23,7 +23,7 @@ func TestInvoke(t *testing.T) {
        var invoked int32
 
        // Create a test function to be invoked
-       if err := fn.New().Create(fn.Function{Runtime: "go", Root: root}); err != nil {
+       if err := fn.New().Create(fn.Function{Runtime: "go", Root: root, Namespace: "foobar"}); err != nil {
                t.Fatal(err)
        }
 
@@ -62,14 +62,24 @@ func TestInvoke(t *testing.T) {
        }
        t.Cleanup(job.Stop)
 
+       usedNs := ""
+       newClient := func(conf ClientConfig, opts ...fn.Option) (*fn.Client, func()) {
+               usedNs = conf.Namespace
+               return NewClient(conf, opts...)
+       }
+
        // Test that the invoke command invokes
-       cmd := NewInvokeCmd(NewClient)
+       cmd := NewInvokeCmd(newClient)
        cmd.SetArgs([]string{})
 
        if err := cmd.Execute(); err != nil {
                t.Fatal(err)
        }
 
+       if usedNs != "foobar" {
+               t.Errorf("bad ns used: %q", usedNs)
+       }
+
        if atomic.LoadInt32(&invoked) != 1 {
                t.Fatal("function was not invoked")
        }
```

Comment (lkingland) [reply cmd/invoke.go:139]: Right, the namespace is unnecessary because the Function's current namespace will be used.
For example, regardless of the user's currently active kubernetes namespace, a request to invoke a Function should always attempt to invoke the function where it actually is deployed.

**Comment by matejvasek** [comment]
@lkingland put on hold because of @salaboy 's PR.

There is no textual merge conflict,
however `fn.Function` has changed, moving Namespace to sub-struct, so there is a conflict.

**Comment by lkingland** [comment]
> @lkingland put on hold because of @salaboy 's PR.
> 
> There is no textual merge conflict, however `fn.Function` has changed, moving Namespace to sub-struct, so there is a conflict.

No problem.  I can update and sneak this in after

File: cmd/invoke.go [hunk 2]
```diff
@@ -135,8 +135,17 @@ func runInvoke(cmd *cobra.Command, args []string, newClient ClientFactory) (err
...
+	client, done := newClient(ClientConfig{Namespace: f.Namespace, Verbose: cfg.Verbose, InsecureSkipVerify: cfg.Insecure})
```
Comment (matejvasek) [inline cmd/invoke.go:148]: This might need update to work with Salaboy's changes.

File: cmd/invoke_test.go [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+}
+
+// TestInvoke_Namespace ensures that invocation uses the Function's namespace
+// despite the currently active.
+func TestInvoke_Namespace(t *testing.T) {
+	root, rm := Mktemp(t)
+	defer rm()
+
+	// Create a Function in a non-active namespace
+	f := fn.Function{Runtime: "go", Root: root, Namespace: "ns"}
```
Comment (matejvasek) [inline cmd/invoke_test.go:85]: And this init too should be updated.

File: cmd/invoke.go (hunk 2 above)
Comment (matejvasek) [inline cmd/invoke.go:148]:
```suggestion
	client, done := newClient(ClientConfig{Namespace: f.Deploy.Namespace, Verbose: cfg.Verbose, InsecureSkipVerify: cfg.Insecure})
```

File: cmd/invoke_test.go (hunk 3 above)
Comment (matejvasek) [inline cmd/invoke_test.go:85]:
```suggestion
	f := fn.Function{Runtime: "go", Root: root, Deploy: fn.DeploySpec{Namespace: "ns"}}
```
